org.gradle.jvmargs=-Xms1G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+PerfDisableSharedMem -Dfile.encoding=UTF-8 -Djava.awt.headless=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.configuration-cache.problems=warn
org.gradle.workers.max=6
org.gradle.console=rich
org.gradle.warning.mode=all

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.1
loader_version=0.16.9

version=1.1.2-fabric+1.21.4(.11)mc
maven_group=net.bichal
fabric_version=0.115.1+1.21.4
archives_base_name=better-player-locator-bar

mod_menu_version=14.0.0
